# docker-compose.yml
version: '3.8'
services:
  server:
    build: .
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    command: air -c .air.toml
    depends_on:
      - db
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: